services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: template_db
            POSTGRES_USER: template_user
            POSTGRES_PASSWORD: template_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
